version: '3.8'

services:
  # 1. Serviço do Banco de Dados
  mongodb:
    image: mongo:6.0-jammy
    container_name: realworld-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - realworld-net

  # 2. Serviço da API REST (Node.js)
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: realworld-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=mongodb://realworld-db:27017/conduit?authSource=admin
      - MONGODB_URI=mongodb://realworld-db:27017/conduit?authSource=admin
      - SECRET=sua_chave_secreta_super_segura_para_gerar_tokens
    depends_on:
      - mongodb
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - realworld-net

volumes:
  mongo_data:

networks:
  realworld-net:
    name: realworld-net
    driver: bridge